definitions:
  models.TurnMCRequest:
    properties:
      turnOnOff:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/healthcheck:
    get:
      description: 현재 서버 상태 체크
      responses:
        "200":
          description: OK
      summary: 상태 체크
      tags:
      - common
  /api/v1/mc/status:
    get:
      description: 마인크래프트 서버 상태 확인
      responses:
        "200":
          description: OK
      summary: 서버 상태 확인
      tags:
      - mc
  /api/v1/mc/turn:
    post:
      consumes:
      - application/json
      description: 마인크래프트 서버 켜기/끄기
      parameters:
      - description: 서버 전원 ON/OFF
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.TurnMCRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 서버 켜기/끄기
      tags:
      - mc
swagger: "2.0"
